### ISSUE TITLE
Cannot add >4 AWS roles to a user

### ISSUE THREAD

**Issue by nonspecialist** [cevoaustralia/google-aws-federator#3]
When attempting to add a fifth AWS role to a user, the tool crashes with a backtrace similar to:

```
$ federator user -U user@example.com add -R arn:aws:iam::123456789012:role/FederatedAdministrator -P arn:aws:iam::123456789012:saml-provider/GoogleApps

Traceback (most recent call last):
  File "/home/user/.local/bin/federator", line 9, in <module>
    load_entry_point('google-aws-federator==0.0.1', 'console_scripts', 'federator')()
  File "/home/user/.local/lib/python2.7/site-packages/federator/__init__.py", line 130, in main
    args.func(args)
  File "/home/user/.local/lib/python2.7/site-packages/federator/__init__.py", line 51, in user_add
    added = user.add_role(roleArn=args['rolearn'], providerArn=args['providerarn'])
  File "/home/user/.local/lib/python2.7/site-packages/federator/federator.py", line 157, in add_role
    response = request.execute()
  File "/usr/lib/python2.7/site-packages/oauth2client/util.py", line 135, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/googleapiclient/http.py", line 832, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 413 when requesting https://www.googleapis.com/admin/directory/v1/users/user%40example.com?alt=json returned "Profile quota is exceeded.: Data is too large for">
```

**Comment by s0enke** [comment]
It seems that this issue is actually a limit in the Google API: http://stackoverflow.com/questions/38024817/maximum-size-of-patch-to-customschemas
